import { DOC_PREFIX } from "../constants"

export const WIDGET_TYPE_MAP_DOC_LINK: Record<string, string> = {
  BAR_PROGRESS_WIDGET: `${DOC_PREFIX}bar-progress`,
  BUTTON_WIDGET: `${DOC_PREFIX}button`,
  CAROUSEL_WIDGET: `${DOC_PREFIX}carousel`,
  CASCADER_WIDGET: `${DOC_PREFIX}cascader`,
  CIRCLE_PROGRESS_WIDGET: `${DOC_PREFIX}circle-progress`,
  CONTAINER_WIDGET: `${DOC_PREFIX}container`,
  DATE_WIDGET: `${DOC_PREFIX}date`,
  DATE_RANGE_WIDGET: `${DOC_PREFIX}date-range`,
  DATE_TIME_WIDGET: `${DOC_PREFIX}date-time`,
  DIVIDER_WIDGET: `${DOC_PREFIX}divider`,
  EDITABLE_TEXT_WIDGET: `${DOC_PREFIX}editable-text`,
  EVENT_CALENDAR_WIDGET: `${DOC_PREFIX}event-calendar`,
  FORM_WIDGET: `${DOC_PREFIX}form`,
  ICON_WIDGET: `${DOC_PREFIX}icon`,
  IMAGE_WIDGET: `${DOC_PREFIX}image`,
  INPUT_WIDGET: `${DOC_PREFIX}input`,
  LIST_WIDGET: `${DOC_PREFIX}list`,
  GRID_LIST_WIDGET: `${DOC_PREFIX}grid-list`,
  MENU_WIDGET: `${DOC_PREFIX}menu`,
  MODAL_WIDGET: `${DOC_PREFIX}modal`,
  MULTISELECT_WIDGET: `${DOC_PREFIX}multi-select`,
  NUMBER_INPUT_WIDGET: `${DOC_PREFIX}number-input`,
  PDF_WIDGET: `${DOC_PREFIX}pdf`,
  RADIO_BUTTON_WIDGET: `${DOC_PREFIX}radio-button`,
  RADIO_GROUP_WIDGET: `${DOC_PREFIX}radio-group`,
  RATE_WIDGET: `${DOC_PREFIX}rate`,
  SELECT_WIDGET: `${DOC_PREFIX}select`,
  STATISTIC_WIDGET: `${DOC_PREFIX}statistic`,
  SWITCH_WIDGET: `${DOC_PREFIX}switch`,
  TABLE_WIDGET: `${DOC_PREFIX}table`,
  TABS_WIDGET: `${DOC_PREFIX}tabs`,
  TEXT_WIDGET: `${DOC_PREFIX}text`,
  TEXTAREA_INPUT_WIDGET: `${DOC_PREFIX}text-area-input`,
  TIME_PICKER_WIDGET: `${DOC_PREFIX}time-picker`,
  TIME_RANGE_WIDGET: `${DOC_PREFIX}time-range`,
  TIMELINE_WIDGET: `${DOC_PREFIX}timeline`,
  UPLOAD_WIDGET: `${DOC_PREFIX}upload`,
  VIDEO_WIDGET: `${DOC_PREFIX}video`,
  // AUDIO_WIDGET: `${DOC_PREFIX}audio`,
  // CHART_WIDGET: `${DOC_PREFIX}chart`,
  // CHAT_WIDGET: `${DOC_PREFIX}chat`,
  // CHECKBOX_GROUP_WIDGET: `${DOC_PREFIX}checkbox-group`,
  // DRIVE_PICKER_WIDGET: `${DOC_PREFIX}drive-picker`,
  // JSON_EDITOR_WIDGET: `${DOC_PREFIX}json-editor`,
  // JSON_SCHEMA_FORM_WIDGET: `${DOC_PREFIX}json-schema-form`,
  // MAP_WIDGET: `${DOC_PREFIX}map`,
  // RANGE_SLIDER_WIDGET: `${DOC_PREFIX}range-slider`,
  // RECORDING_WIDGET: `${DOC_PREFIX}recording`,
  // RICH_TEXT_WIDGET: `${DOC_PREFIX}rich-text`,
  // SLIDER_WIDGET: `${DOC_PREFIX}slider`,
  // STEPS_WIDGET: `${DOC_PREFIX}steps`,
  // SWITCH_GROUP_WIDGET: `${DOC_PREFIX}switch-group`,
  // DATA_GRID_WIDGET: `${DOC_PREFIX}data-grid`,
  // IFRAME_WIDGET: `${DOC_PREFIX}iframe`,
}
